# Generated by Django 4.1.7 on 2023-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
